### ISSUE TITLE
"Add attack/damage buttons to item inventory list" option does not work with Tidy5e Sheet

### ISSUE THREAD

**Issue by watermelonwolverine** [tposney/midi-qol#1245]
Hello,

I noticed, that the "Add attack/damage buttons to item inventory list" option does not work with the Tidy5e module.

Modules enabled:

libWrapper 1.12.13.0
MidiQOL version 11.3.18
socketlib 1.0.13
Tidy5e Sheet v0.10.1

**Comment by tposney** [comment]
Apologies: this is not the live repo for midi-qol it is https://gitlab.com/tposney/midi-qol.
I will make a note on the front to prevent others going to the wrong spot.

For you issue I have moved to the newer version of tidy sheet authoered by kgar - you can get it here
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/latest/download/module.json
